version: '3.8'

services:
  frontend:
    image: messakami/tp-svelte-frontend:latest
    restart: always
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    image: messakami/tp-fastify-backend:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production 